import { mkdir, writeFile } from "node:fs/promises";
import { basename, dirname } from "node:path";
import { pick } from "lodash-es";
import openapiTS, { astToString, OpenAPI3, PathsObject } from "openapi-typescript";
import { FollowApiConfig } from "./follow-api.config";

const doc = (await (await fetch(FollowApiConfig.spec)).json()) as OpenAPI3;

doc.paths = pick(doc.paths || {}, FollowApiConfig.paths) as PathsObject;

const ast = await openapiTS(doc, {});
const contents = astToString(ast);
await mkdir(dirname(FollowApiConfig.generatedPath), { recursive: true });
await writeFile(
  FollowApiConfig.generatedPath,
  `// Auto-generated by ${basename(process.argv[1])}, please do not modify by hand.
 
export const baseUrl = ${JSON.stringify(FollowApiConfig.root)};

${contents}`
);
